DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE FAULTREPORT CASCADE CONSTRAINTS;
DROP TABLE OUTLET CASCADE CONSTRAINTS;
DROP TABLE VEHICLE CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE RAGREEMENT CASCADE CONSTRAINTS;

CREATE TABLE EMPLOYEE(
 	EmpNo NUMBER(10) PRIMARY KEY NOT NULL,
 	Fname VARCHAR2(99),
 	Lname VARCHAR2(99),
 	Position VARCHAR2(200),
 	Phone VARCHAR2(15) UNIQUE,
 	Email VARCHAR2(200) UNIQUE,
 	DOB DATE,
 	Gender CHAR(1),
 	Salary NUMBER(8,2),
 	HireDate date DEFAULT SYSDATE,
 	outNo NUMBER(10),
 	SupervisorNo NUMBER(10)	
);

CREATE TABLE FAULTREPORT(
	ReportNum VARCHAR2(16) PRIMARY KEY NOT NULL,
	DateChecked date DEFAULT SYSDATE NOT NULL,
	Comments VARCHAR2(4000) NOT NULL,
	EmpNo NUMBER(10) ,
	LicenseNo VARCHAR2(10),
	RentalNo VARCHAR2(100),
	CONSTRAINT EmpNo_fk FOREIGN KEY (EmpNo) REFERENCES Employee(EmpNo)
);

CREATE TABLE OUTLET(
	outNo NUMBER(10) PRIMARY KEY NOT NULL,
	Street VARCHAR(200),
 	City VARCHAR2(100),
 	State CHAR(2),
 	ZipCode NUMBER(5),
	Phone VARCHAR2(15),
	ManagerNo NUMBER(10)
);
 
CREATE TABLE VEHICLE(
	LicenseNo VARCHAR2(10) PRIMARY KEY NOT NULL,
	Make VARCHAR2(30),
	Model VARCHAR2(100) NOT NULL,
	Color VARCHAR2(100),
	Year NUMBER(4) NOT NULL,
	NoDoors NUMBER(9),
	Capacity NUMBER(20),
	DailyRate NUMBER(5,2) NOT NULL,
	InspectionDate DATE,
 	outNo NUMBER(10),
	CONSTRAINT outNum_fk FOREIGN KEY (outNo) REFERENCES Outlet(outNo),
	CONSTRAINT Year_ck CHECK(Year > 2006)
);

CREATE TABLE CLIENT(
 	ClientNo NUMBER(10) PRIMARY KEY NOT NULL,
 	ClientName VARCHAR2(250),
 	Street VARCHAR(200),
 	City VARCHAR2(100),
 	State CHAR(2),
 	ZipCode NUMBER(5),
 	WebAddress VARCHAR2(200),
 	Contact_FName VARCHAR2(99),
 	Contact_LName VARCHAR2(99),
 	Phone VARCHAR2(15),
 	Email VARCHAR2(200)
);

CREATE TABLE RAGREEMENT(
	RentalNo VARCHAR2(100) PRIMARY KEY NOT NULL,
	StartDate DATE DEFAULT SYSDATE,
	ReturnDate DATE, 
	MileageBefore NUMBER(6) NOT NULL,
	MileageAfter NUMBER(6),
	InsuranceType VARCHAR2(200) NOT NULL,
	ClientNo NUMBER(10),
	LicenseNo VARCHAR2(10),
	CONSTRAINT ClientNum_fk FOREIGN KEY (ClientNo) REFERENCES Client(ClientNo), 
	CONSTRAINT ReturnDate_ck CHECK (ReturnDate >= StartDate),
	CONSTRAINT MileageBefore_ck CHECK (MileageBefore <= MileageAfter)
);

ALTER TABLE EMPLOYEE
	ADD CONSTRAINT outletNo_fk 
	FOREIGN KEY (outNo) 
	REFERENCES Outlet(outNo);
	
ALTER TABLE EMPLOYEE
	ADD CONSTRAINT SupervisorNo_fk 
	FOREIGN KEY (SupervisorNo) 
	REFERENCES Employee(EmpNo);	

ALTER TABLE EMPLOYEE
	ADD CONSTRAINT Salary_ck
	CHECK (Salary > 0);
	
ALTER TABLE VEHICLE
	ADD CONSTRAINT LicenseNo_fk 
	FOREIGN KEY (LicenseNo) 
	REFERENCES Vehicle(LicenseNo);
	
ALTER TABLE FAULTREPORT
	ADD CONSTRAINT LicenseNum_fk 
	FOREIGN KEY (LicenseNo) 
	REFERENCES Vehicle(LicenseNo);

ALTER TABLE FAULTREPORT	
	ADD CONSTRAINT RentalNo_fk 
	FOREIGN KEY (RentalNo) 
	REFERENCES RAGREEMENT(RentalNo);